name: Build and Deploy Docker Image

on:
  release:
    types:
      - published

jobs:
  build-and-deploy:
    runs-on: arc-runner-set
    if: github.repository == 'homelab-peej/ping-server'
    permissions:
      contents: read
      packages: write
      pull-requests: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        tags: ghcr.io/homelab-peej/ping-server:${{ github.ref_name }},ghcr.io/homelab-peej/ping-server:latest
        push: true
